### ISSUE TITLE
[iotivity][linux] how to make ocf-server & ocf-client run on linux platform

### ISSUE THREAD

**Issue by ustccw** [iotivity/iotivity-lite#4]
Hi all,
It looks like can not work well on my ubuntu18.04, when i update `iotivity-constrained` to `iotivity-lite`.

What I did is just `make` and run `./server` & `./client`.

- On `iotivity-constrained` SDK, it still looks like work well now.
![ESP-20200403-09](https://user-images.githubusercontent.com/24221485/78347565-45557880-75d3-11ea-9866-82caffa7790c.png)

- On `iotivity-lite` SDK, it still looks like can not communicate with each other.
![ESP-20200403-08](https://user-images.githubusercontent.com/24221485/78347582-4ab2c300-75d3-11ea-864d-994f94021a3e.png)

What should I do to make `iotivity-lite` works on linux?

**Comment by ustccw** [comment]
@kmaloor Would you like to give me some advice?

**Comment by kmaloor** [comment]
@ustccw The old iotivity-constrained repository has since long been deprecated. Please always refer to the iotivity-lite repo as it is current and actively maintained.
The issue you're having is likely because SECURE=1 has been made the default in the current IoTivity-Lite Makefile. That was not the case earlier. So, to make it work, you'd need to go through onboarding and provisioning steps with an Onboarding Tool (OBT). There's a sample OBT named "onboarding_tool" that's available in the Linux build. You can find some basic guidelines for using the OBT under the "Onboarding and Provisioning" section of the top-level README in the repository.

Without going through those provisioning steps, the Client would simply attempt to interact with the Server and fail. That's essentially what you're seeing in your logs.
If you want to see similar results now as before, simply build with "make SECURE=0". That's just an option for development purposes, but however the security layer is mandatory on any OCF Device.

**Comment by ustccw** [comment]
@kmaloor Thanks your detailed reply, it works when `make SECURE=0`.

We will try to `make SECURE=1` with steps OBT.
