### ISSUE TITLE
ERROR: oc_tls.c:2511 <oc_tls_init_connection>: error: device not in DOS_RFNOP state

### ISSUE THREAD

**Issue by luoweimin-git** [iotivity/iotivity-lite#498]
hello everybody!
 firstly, i make sdk without SECURE (make DEBUG=1 IPV4=1 PUSH=1 CREATE=1 SECURE=0) , simpleclient and simpleserver can run correctly. then i want enable SECURE function(make DEBUG=1 IPV4=1 PUSH=1 CREATE=1 SECURE=1), when i run simpleclient and simpleserver ,some ERROR happen,The error log is as follows:

xyx@xyx-virtual-machine:~/workspace/tmp/iotivity-lite/iotivity-lite/port/linux$ ./simpleclient
Resource /a/light hosted at endpoints:
coaps://192.168.146.130:38249
[OC 2023-08-19T01:10:24.911421Z] ERROR: oc_tls.c:2511 <oc_tls_init_connection>: error: device not in DOS_RFNOP state

Please give me some advise and steps, thank you very much !

**Comment by jkralik** [comment]
Hi @luoweimin-git,

It seems that using `simpleclient` with the secured device `simpleserver` might not be suitable due to the absence of ownership functionality.

Since you have secured `simpleserver`, the recommended approach is to utilize the terminal onboarding tool (obt) or the [plgd-dev/client-application(web-ui)](https://github.com/plgd-dev/client-application). Through this, you can discover `simpleserver` as an unowned device, establish ownership, and then proceed with your interactions.

In case you're developing a device with cloud functionality, you can onboard the device to the [plgd-dev/hub](https://docs.plgd.dev/docs/quickstart/deploy-plgd-hub/#plgd-bundle).

By the way, I'd suggest considering the adoption of CMake over make, as make might be deprecated in the future.

**Comment by jkralik** [comment]
Pls fill free to reopen issue. Thx
