### ISSUE TITLE
Compilation error when applying with NDK21, ABI=armeabi, API=23

### ISSUE THREAD

**Issue by Askidea** [iotivity/iotivity-lite#545]
Hi, everyone

An error occurred during compilation as follows. Who can help me solve this?

* **Source version:** commit fc89bd6

Since I am compiling using old bridging sources, I am working with the following compilation options. 
* **Compilation options**
```
NDK21
CC = /usr/bin/gcc
API=23
ABI=armeabi
```

* **Compile command**
`~/github/iotivity-lite/port/android$ make NDK_HOME=~/toolchains/ndk21-android-arm-23 DEBUG=1
`
* **Compilation error log**
```
/usr/bin/gcc -c -o arm-linux-androideabi-obj/server/ipadapter.o ipadapter.c -fPIC -fno-asynchronous-unwind-tables -fno-omit-frame-pointer -ffreestanding -Os -fno-stack-protector -ffunction-sections -fdata-sections -fno-strict-overflow -I./ -I../../include/ -I../../deps/tinycbor/src -I../../ -std=gnu99 -Wall -Wextra -Werror -Wno-error=deprecated-declarations -pedantic -DLONG_BIT=64 -D__ANDROID_MIN_SDK_VERSION__=23 -DOC_CLOUD -g -O0 -I../../deps/mbedtls/include -Wno-error=unused -DOC_SECURITY -DOC_DEBUG -DOC_LOG_MAXIMUM_LEVEL=8 -DOC_PKI -DOC_DYNAMIC_ALLOCATION -DOC_INTROSPECTION -DOC_IDD_API -DOC_IPV4 -DOC_TCP -DOC_SERVER
ipadapter.c:21:10: fatal error: android/api-level.h: No such file or directory
   21 | #include <android/api-level.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:321: arm-linux-androideabi-obj/server/ipadapter.o] Error 1
```

**Comment by Danielius1922** [comment]
@Askidea 

Compiles fine for me on x86_64: 

1. I've downloaded NDK r21e from https://github.com/android/ndk/wiki/Unsupported-Downloads and extracted it to ~/android-ndk-r21e-linux-x86_64
2. cd ~/android-ndk-r21e-linux-x86_64/android-ndk-r21e/build/tools && python3 ./make_standalone_toolchain.py --arch x86_64 --api 23 --install-dir ~/android-ndk21-api23
3. cd iotivity-lite/port/android && make NDK_HOME=~/android-ndk21-api23 ANDROID_API=23 ANDROID_ABI=x86_64 CLOUD=1 DEBUG=1

It compiles for me without issues. 

Now hopefully, it's not a problem of arm vs x86, because I don't have the means of debugging that. The only other thing I've noticed is the compiler. My `CC` is `~/android-ndk21-api23/bin/x86_64-linux-android-gcc`

```shell
$ ~/android-ndk21-api23/bin/x86_64-linux-android-gcc --version

Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn)
Target: x86_64-unknown-linux-android23
Thread model: posix
InstalledDir: ~/android-ndk21-api23/bin
```

If I recall correctly, `<android/api-level.h>` is an Android system header that should be recognized by the Android compilers. I suspect that your build system is for some reason attempting to compile the port with a non-Android compiler. 

What is the output when you run `/usr/bin/gcc --version`? What `make` command do you execute to compile the Android port?

**Comment by Askidea** [comment]
@Danielius1922 
It was built by using `arm-linux-androideabi-gcc` and removing `-Werror` from `WARNING_FLAGS` in _Makefile_.

**Comment by Askidea** [comment]
@Danielius1922 

I share the gcc version information as you guided

**CASE #1 : /usr/bin/gcc**
`Makefile:101: *** gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 Copyright (C) 2021 Free Software Foundation, Inc. This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE..  Stop.`

**CASE #2 : NDK21, (arm64 or armeabi)**
`Makefile:100: *** Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn) Target: armv7a-unknown-linux-android23 Thread model: posix InstalledDir: /home/david/toolchains/ndk21-android-arm-23/bin.  Stop.
`
**CASE #2 : NDK25, (arm64 or armeabi)**
`Makefile:100: *** Android (9352603, based on r450784d1) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6) Target: aarch64-unknown-linux-android23 Thread model: posix InstalledDir: /home/david/toolchains/ndk25-android-arm64-23/bin.  Stop.`

**Comment by Danielius1922** [comment]
@Askidea 

Yeah the first case is a Linux gcc, that won't work with the android port. The other cases should work correctly, they use the special android compilers that recognize the `<android/api-level.h>` header.

What's the first case? Is something setting `CC` to `/usr/bin/gcc` in your environment?

**Comment by Askidea** [comment]
@Danielius1922 

There is no particular reason to use /usr/bin/gcc. In issue #534, probably I guess I misunderstood your comment because library compilation using arm-linux-androideabi-gcc initially failed.
Thank you for your feedback.

**Comment by Danielius1922** [comment]
@Askidea Yeah sorry if I was unclear. Does the compilation work with the android compilers or do you still have some issues?

**Comment by Askidea** [comment]
@Danielius1922 
I am testing NDK25 and NDK21 by building(without `-Werror` or with only `-Wall`) them with `arm64-v8a` and `armeabi` architectures. If another issue comes up, I will post again.
I think this issue can be closed.
