### ISSUE TITLE
Error compiling...

### ISSUE THREAD

**Issue by alexe100** [iotivity/iotivity-lite#637]
In ubuntu 20:

~/Downloads/iotivity-lite/port/linux$ make DEBUG=1 IPV4=1 TCP=1 SECURE=0

returns:

In file included from ../../apps/simpleserver_pki.c:20:
../../include/oc_pki.h:38:10: fatal error: mbedtls/build_info.h: No such file or directory
   38 | #include <mbedtls/build_info.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:563: simpleserver_pki] Error 1

I have mbedtls installed but the file build_info.h is not there

Thanks

**Comment by Danielius1922** [comment]
Mbedtls shouldn't be used when `SECURE=0`, try adding `PKI=0` to your command? But `PKI=0` should be force if `SECURE=0`, so I'll do that.

The build should use local checkout of mbedtls anyway that is the `deps/mbedtls` folder. I think the issue is that we're including mbedtls in code using `<>` instead `""`, which means that mbedtls headers found in standard system folders will be used instead of the local headers. Which is wrong, I'll change the includes to use `""`.

But you be able to make the current version work too. It seems you have an older mbedtls build in some standard system folder. IoT build needs mbedtls 3.1 (or 3.5.0 if you use the MBEDTLS_FORCE_3_5_0=1 switch). We patch the mbedtls too, so you need to run the `Makefile` or `cmake` build of IoT first, this patches the mbedtls and then install mbedtls. Do you need to use `Makefile` or is `cmake` available? The cmake build installs mbedtls automatically, with Makefile you need to do it manually. Probably something like:

```sh
cd deps/mbedtls
make
sudo make install
```
